version: "3.8"
services:
  frontend:
    build: ./frontend
    image: frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    restart: unless-stopped

  backend:
    build: ./backend
    image: backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    restart: unless-stopped
