name: Backend Pipeline

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request: 
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        working-directory: ./backend/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.BACKEND_APP_YML }}" > src/main/resources/application.yml

      - name: Build Backend
        run: mvn clean install
  
      - name: Run Unit Tests
        run: mvn test

      - name: Generate Coverage
        run: mvn jacoco:report

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/site/jacoco/jacoco.xml
          fail_ci_if_error: true

      # Optional deploy step
      # - name: Deploy backend
      #   run: <deploy command>
