name: Build & Deploy Docker Images to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Build frontend and backend Docker images
      - name: Build frontend image
        run: docker build -t frontend:latest ./frontend

      - name: Build backend image
        run: docker build -t backend:latest ./backend

      # 3. Save images as tar files
      - name: Save Docker images
        run: |
          mkdir -p docker-images
          docker save frontend:latest -o docker-images/frontend.tar
          docker save backend:latest -o docker-images/backend.tar

      # 4. Setup SSH key
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 5. Setup known hosts to avoid host key verification errors
      - name: Setup known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_HOST_KEY }}" > ~/.ssh/known_hosts

      # 6. Copy Docker images to EC2
      - name: Copy Docker images
        run: |
          scp -i ~/.ssh/id_rsa docker-images/*.tar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/TutorLink/

      # 7. Load images and deploy on EC2
      - name: Deploy Docker images on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/TutorLink
            docker load -i frontend.tar
            docker load -i backend.tar
            docker compose down
            docker compose up -d
          EOF
