name: Build & Deploy Docker Images to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
    # 1. Checkout repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Build Docker images
    - name: Build backend image
      run: docker build -t backend:latest ./backend

    - name: Build frontend image
      run: docker build -t frontend:latest ./frontend

    # 3. Save images as tar files
    - name: Save Docker images
      run: |
        mkdir -p docker-images
        docker save backend:latest -o docker-images/backend.tar
        docker save frontend:latest -o docker-images/frontend.tar
        chmod 644 docker-images/backend.tar docker-images/frontend.tar
        ls -l docker-images/
        ls -l docker-compose.yml

    # 4. Prepare SCP folder
    - name: Prepare files for SCP
      run: |
        mkdir -p scp
        cp docker-images/backend.tar scp/backend.tar
        cp docker-images/frontend.tar scp/frontend.tar
        cp docker-compose.yml scp/docker-compose.yml
        ls -l scp/

    # 5. Copy files to EC2 (disable tar)
    - name: Copy files to EC2
      uses: appleboy/scp-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: |
          scp/backend.tar
          scp/frontend.tar
          scp/docker-compose.yml
        target: /home/ubuntu/app
        tar: false

    # 6. SSH to EC2 and deploy
    - name: Deploy Docker images on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mkdir -p ~/app/docker-images
          mv ~/app/backend.tar ~/app/docker-images/
          mv ~/app/frontend.tar ~/app/docker-images/
          cd ~/app/docker-images
          docker load -i backend.tar
          docker load -i frontend.tar
          cd ~/app
          docker compose down
          docker compose up -d
