name: Deploy Frontend & Backend to EC2

on:
  push:
    branches:
      - main  # change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Upload entire repo to EC2
    - name: Upload project to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "/home/${{ secrets.EC2_USER }}/app"

    # SSH and build/run both containers
    - name: SSH to EC2 and deploy with docker-compose
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/app
          docker compose down
          docker compose up -d --build
