name: Build & Deploy Docker Images to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # ===== FRONTEND =====
      - name: Create frontend .env
        run: |
          echo "${{ secrets.FRONTEND_ENV_FILE }}" > frontend/.env

      - name: Build frontend Docker image
        run: docker build -t frontend:latest ./frontend

      # ===== BACKEND =====
      - name: Create backend application.yml
        run: |
          mkdir -p backend/src/main/resources
          echo "${{ secrets.BACKEND_APP_YML }}" > backend/src/main/resources/application.yml

      - name: Build backend Docker image
        run: docker build -t backend:latest ./backend

      # ===== PACKAGE DOCKER IMAGES =====
      - name: Save Docker images
        run: |
          mkdir docker-images
          docker save frontend:latest -o docker-images/frontend.tar
          docker save backend:latest -o docker-images/backend.tar

      # ===== COPY IMAGES TO EC2 =====
      - name: Copy Docker images to EC2
        run: |
          scp -i ~/.ssh/id_rsa \
            docker-images/frontend.tar \
            docker-images/backend.tar \
            ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/TutorLink/

      # ===== LOAD & RUN ON EC2 =====
      - name: Load images and restart containers
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/TutorLink
            docker load -i frontend.tar
            docker load -i backend.tar
            docker compose down
            docker compose up -d
          EOF
