name: DAST Scan

on:
  workflow_dispatch: # manual trigger
  # workflow_run:
  #   workflows: ["Deploy Pipeline"]
  #   types:
  #     - completed

jobs:
  dast:
    name: DAST Scan - OWASP ZAP
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug secret
        run: |
          if [ -z "${{ secrets.STAGING_URL }}" ]; then
            echo "STAGING_URL is empty"
            exit 1
          else
            echo "STAGING_URL is set"
          fi
          
      - name: Test connectivity
        run: curl -I ${{ secrets.STAGING_URL }}

      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: ${{ secrets.STAGING_URL }}
          cmd_options: >
            -r zap-report.html
            -j zap-report.json
            -d

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-html-report
          path: zap-report.html

      - name: Upload JSON report artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-json-report
          path: zap-report.json
